### ISSUE TITLE
GSoC

### ISSUE THREAD

**Issue by burdges** [canndrew/gnunet-rs#2]
I listed gnunet-rs in the [proposed GSoC projects](https://gnunet.org/gsoc-2016) so if any students are interested in working on it then let me know.  :)

**Comment by canndrew** [comment]
Closing because we have a student. What's happening with this though? GSoC should be starting around now shouldn't it?

**Comment by burdges** [comment]
midterm blog post : https://gnunet.org/node/2624
async branch of his repo : https://github.com/kc1212/gnunet-rs/pull/2
